################################################################################
# The MIT License (MIT)
#
# Copyright (c) 2014 Abi George Ullattil (Vite Falcon)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
################################################################################
SET(VITELIBTEST_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

FILE(GLOB VITELIB_CONFIG_TESTS_SOURCES "${VITELIBTEST_SOURCE_DIR}/config/*.cpp")
FILE(GLOB VITELIB_CONFIG_TESTS_HEADERS "${VITELIBTEST_SOURCE_DIR}/config/*.h")
FILE(GLOB VITELIB_STRING_TESTS "${VITELIBTEST_SOURCE_DIR}/string/*.cpp")
FILE(GLOB VITELIB_VARIANT_TESTS "${VITELIBTEST_SOURCE_DIR}/variant/*.cpp")
FILE(GLOB VITELIB_TEST_SOURCES "${VITELIBTEST_SOURCE_DIR}/*.cpp")
FILE(GLOB VITELIB_TEST_HEADERS "${VITELIBTEST_SOURCE_DIR}/*.h")


SET(VITELIB_SRCGROUP_TESTS Tests)
SOURCE_GROUP(${VITELIB_SRCGROUP_TESTS} FILES ${VITELIB_TEST_HEADERS} ${VITELIB_TEST_SOURCES})
SOURCE_GROUP(${VITELIB_SRCGROUP_TESTS}\\config FILES ${VITELIB_CONFIG_TESTS_HEADERS} ${VITELIB_CONFIG_TESTS_SOURCES})
SOURCE_GROUP(${VITELIB_SRCGROUP_TESTS}\\string FILES ${VITELIB_STRING_TESTS})
SOURCE_GROUP(${VITELIB_SRCGROUP_TESTS}\\variant FILES ${VITELIB_VARIANT_TESTS})

SET(VITELIB_TEST_HEADER_FILES
    ${VITELIB_TEST_HEADERS}
	${VITELIB_CONFIG_TESTS_HEADERS}
)
SET(VITELIB_TEST_SOURCE_FILES
    ${VITELIB_TEST_SOURCES}
    ${VITELIB_CONFIG_TESTS_SOURCES}
    ${VITELIB_STRING_TESTS}
    ${VITELIB_VARIANT_TESTS}
)

SET(VITELIB_TEST_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/CMake")

SET(VITELIB_TEST_CMAKE_FILES
	${CMAKE_CURRENT_SOURCE_DIR}/CMake/vite_lib_test_dependencies.cmake
	${CMAKE_CURRENT_SOURCE_DIR}/CMake/vite_lib_test_files.cmake
)

SET(VITELIB_TEST_SRCGROUP_CMAKE CMake)
SOURCE_GROUP(${VITELIB_TEST_SRCGROUP_CMAKE} FILES ${VITELIB_TEST_CMAKE_FILES})