set(VITELIBTEST_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

file(GLOB VITELIB_STRING_TESTS "${VITELIBTEST_SOURCE_DIR}/string/*.cpp")
file(GLOB VITELIB_VARIANT_TESTS "${VITELIBTEST_SOURCE_DIR}/variant/*.cpp")
file(GLOB VITELIB_TEST_SOURCES "${VITELIBTEST_SOURCE_DIR}/*.cpp")
file(GLOB VITELIB_TEST_HEADERS "${VITELIBTEST_SOURCE_DIR}/*.h")


set(VITELIB_SRCGROUP_TESTS Tests)
source_group(${VITELIB_SRCGROUP_TESTS} FILES ${VITELIB_TEST_HEADERS} ${VITELIB_TEST_SOURCES})
source_group(${VITELIB_SRCGROUP_TESTS}\\string FILES ${VITELIB_STRING_TESTS})
source_group(${VITELIB_SRCGROUP_TESTS}\\variant FILES ${VITELIB_VARIANT_TESTS})

set(VITELIB_TEST_HEADER_FILES
    ${VITELIB_TEST_HEADERS}
)
set(VITELIB_TEST_SOURCE_FILES
    ${VITELIB_TEST_SOURCES}
    ${VITELIB_STRING_TESTS}
    ${VITELIB_VARIANT_TESTS}
)

SET(VITELIB_TEST_CMAKE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/CMake")

SET(VITELIB_TEST_CMAKE_FILES
	${CMAKE_CURRENT_SOURCE_DIR}/CMake/vite_lib_test_dependencies.cmake
	${CMAKE_CURRENT_SOURCE_DIR}/CMake/vite_lib_test_files.cmake
)

SET(VITELIB_TEST_SRCGROUP_CMAKE CMake)
SOURCE_GROUP(${VITELIB_TEST_SRCGROUP_CMAKE} FILES ${VITELIB_TEST_CMAKE_FILES})