file(GLOB VITELIB_STRING_HEADERS "${VITELIB_SOURCE_DIR}/vite/string/*.h")
file(GLOB VITELIB_STRING_SOURCES "${VITELIB_SOURCE_DIR}/vite/string/*.cpp")

file(GLOB VITELIB_VARIANT_HEADERS "${VITELIB_SOURCE_DIR}/vite/variant/*.h")
file(GLOB VITELIB_VARIANT_SOURCES "${VITELIB_SOURCE_DIR}/vite/variant/*.cpp")

file(GLOB VITELIB_ROOT_HEADERS "${VITELIB_SOURCE_DIR}/vite/*.hpp")

set(VITELIB_SRCGROUP_SOURCE Source)
# - Root headers
source_group(${VITELIB_SRCGROUP_SOURCE} FILES ${VITELIB_ROOT_HEADERS})
# - String file
source_group(${VITELIB_SRCGROUP_SOURCE}\\string FILES
	${VITELIB_STRING_HEADERS}
	${VITELIB_STRING_SOURCES}
)
# - Variant files
source_group(${VITELIB_SRCGROUP_SOURCE}\\variant FILES
	${VITELIB_VARIANT_HEADERS}
	${VITELIB_VARIANT_SOURCES}
)

set(VITELIB_HEADER_FILES
	${VITELIB_ROOT_HEADERS}
	${VITELIB_STRING_HEADERS}
	${VITELIB_VARIANT_HEADERS}
)

set(VITELIB_SOURCE_FILES
	${VITELIB_STRING_SOURCES}
	${VITELIB_VARIANT_SOURCES}
)